spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://120.76.216.102:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: letl
    password: Gst2019!Data.2018
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
  servlet:
    context-path: /manager

